var allitems = {
    "main.html" : {
  "EASTER DECOR": {
    "Medium Dancing Bunny": {
      "img": "",
      "price": "21.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'000054",
      "onhold": false,
      "bought": false
    },
    "Mama & baby goose": {
      "img": "",
      "price": "34.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0001N6",
      "onhold": false,
      "bought": false
    },
    "Easter Bunny Garden Pic": {
      "img": "",
      "price": "28.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0001QS",
      "onhold": false,
      "bought": false
    },
    "Nibbles Bunny with Hydrangea": {
      "img": "",
      "price": "32.00",
      "single": false,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0003NC",
      "stock": 2,
      "itemsOnHold": 0,
      "itemsBought": 0
    },
    "Mom's Bunny with Yellow Tulips": {
      "img": "",
      "price": "24.50",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0003ND",
      "onhold": false,
      "bought": false
    },
    "Grass Table Runner - 12x47": {
      "img": "",
      "price": "24.50",
      "single": false,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0003NG",
      "stock": 2,
      "itemsOnHold": 0,
      "itemsBought": 0
    },
    "Bunny Embossed Rectangle Platter": {
      "img": "",
      "price": "27.50",
      "single": false,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0003NH",
      "stock": 2,
      "itemsOnHold": 0,
      "itemsBought": 0
    },
    "Bunny Nesting Dishes - Set of 2": {
      "img": "",
      "price": "26.00",
      "single": false,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0003NI",
      "stock": 3,
      "itemsOnHold": 0,
      "itemsBought": 0
    },
    "Bunny Friend - 9x4 5x12": {
      "img": "",
      "price": "41.50",
      "single": false,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0003NK",
      "stock": 4,
      "itemsOnHold": 0,
      "itemsBought": 0
    },
    "Bunny Friend - 6x5x16": {
      "img": "",
      "price": "45.95",
      "single": false,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0003NL",
      "stock": 4,
      "itemsOnHold": 0,
      "itemsBought": 0
    },
    "Bunny Friend - 8x4x18": {
      "img": "",
      "price": "50.50",
      "single": false,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0003NN",
      "stock": 3,
      "itemsOnHold": 0,
      "itemsBought": 0
    },
    "Tall Sitting Wooden Bunny - 5x11": {
      "img": "",
      "price": "34.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0003NR",
      "onhold": false,
      "bought": false
    },
    "Sniffing Wooden Bunny - 8x18": {
      "img": "",
      "price": "44.00",
      "single": false,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0003NQ",
      "stock": 2,
      "itemsOnHold": 0,
      "itemsBought": 0
    },
    "Brown Ceramic Bunny": {
      "img": "",
      "price": "12.95",
      "single": false,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0003TD",
      "stock": 2,
      "itemsOnHold": 0,
      "itemsBought": 0
    },
    "Carrot wall decor": {
      "img": "",
      "price": "24.99",
      "single": false,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0003WE",
      "stock": 3,
      "itemsOnHold": 0,
      "itemsBought": 0
    }
  },
  "FALL": {
    "Cassia Clove Mercury Pumpkin": {
      "img": "",
      "price": "26.00",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'000055",
      "onhold": false,
      "bought": false
    },
    "Ceramic pumpkin": {
      "img": "",
      "price": "28.50",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'00005B",
      "onhold": false,
      "bought": false
    },
    "Copper pumpkin": {
      "img": "",
      "price": "19.99",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'00006B",
      "onhold": false,
      "bought": false
    },
    "cream mini pumpkin": {
      "img": "",
      "price": "24.95",
      "single": false,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'00006J",
      "stock": 2,
      "itemsOnHold": 0,
      "itemsBought": 0
    },
    "Door swag": {
      "img": "",
      "price": "34.99",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'000078",
      "onhold": false,
      "bought": false
    },
    "Garland": {
      "img": "",
      "price": "12.99",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'00009C",
      "onhold": false,
      "bought": false
    },
    "Grateful box": {
      "img": "",
      "price": "21.99",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0000AS",
      "onhold": false,
      "bought": false
    },
    "Jute Woven Pumpkin": {
      "img": "",
      "price": "23.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0000CR",
      "onhold": false,
      "bought": false
    },
    "Med printed pink pumpkin": {
      "img": "",
      "price": "29.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0000EP",
      "onhold": false,
      "bought": false
    },
    "MEDIUM PUMPKIN": {
      "img": "",
      "price": "15.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0000EU",
      "onhold": false,
      "bought": false
    },
    "Navy vase holiday floral": {
      "img": "",
      "price": "38.00",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0000FU",
      "onhold": false,
      "bought": false
    },
    "Pile of pumpkins 50 cents": {
      "img": "",
      "price": "32.95",
      "single": false,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0000IM",
      "stock": 2,
      "itemsOnHold": 0,
      "itemsBought": 0
    },
    "Pumpkin": {
      "img": "",
      "price": "18.00",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0000J2",
      "onhold": false,
      "bought": false
    },
    "Pumpkin ivory": {
      "img": "",
      "price": "12.99",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0000J3",
      "onhold": false,
      "bought": false
    },
    "Pumpkin Patch Mini": {
      "img": "",
      "price": "15.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0000J4",
      "onhold": false,
      "bought": false
    },
    "Pumpkin runner": {
      "img": "",
      "price": "24.99",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0000J5",
      "onhold": false,
      "bought": false
    },
    "PUMPKIN SIGN": {
      "img": "",
      "price": "12.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0000J6",
      "onhold": false,
      "bought": false
    },
    "pumpkin tin yard sign/table sign": {
      "img": "",
      "price": "26.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0000J7",
      "onhold": false,
      "bought": false
    },
    "RTC Pedestal display Medium": {
      "img": "",
      "price": "22.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0000KL",
      "onhold": false,
      "bought": false
    },
    "set of 4 teal pumpkin placemats": {
      "img": "",
      "price": "28.84",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0000L0",
      "onhold": false,
      "bought": false
    },
    "Sm printed pink pumpkin": {
      "img": "",
      "price": "24.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0000LC",
      "onhold": false,
      "bought": false
    },
    "Stacked pumpkin sign": {
      "img": "",
      "price": "55.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0000MF",
      "onhold": false,
      "bought": false
    },
    "Thankful box": {
      "img": "",
      "price": "26.99",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0000N0",
      "onhold": false,
      "bought": false
    },
    "Velour pumpkin": {
      "img": "",
      "price": "14.99",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0000OF",
      "onhold": false,
      "bought": false
    },
    "Weighted gnome": {
      "img": "",
      "price": "21.99",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0000OQ",
      "onhold": false,
      "bought": false
    },
    "Wheat bundle": {
      "img": "",
      "price": "19.99",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0000OR",
      "onhold": false,
      "bought": false
    },
    "White pumpkin swag": {
      "img": "",
      "price": "29.99",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0000P1",
      "onhold": false,
      "bought": false
    },
    "Grapevine Pumpkin Wreath": {
      "img": "",
      "price": "36.00",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0000TT",
      "onhold": false,
      "bought": false
    },
    "Bowl of pumpkins": {
      "img": "",
      "price": "35.00",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0000TV",
      "onhold": false,
      "bought": false
    },
    "Triple black pumpkin": {
      "img": "",
      "price": "79.00",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0000TX",
      "onhold": false,
      "bought": false
    },
    "Large Ceramic Pumpkin": {
      "img": "",
      "price": "28.00",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0000X4",
      "onhold": false,
      "bought": false
    },
    "lacquer Pumpkin block": {
      "img": "",
      "price": "12.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0001BQ",
      "onhold": false,
      "bought": false
    },
    "Large printed pink pumpkin": {
      "img": "",
      "price": "34.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0001BX",
      "onhold": false,
      "bought": false
    },
    "Pink pumpkin  (floral)": {
      "img": "",
      "price": "38.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0001EF",
      "onhold": false,
      "bought": false
    },
    "striped pumpkins": {
      "img": "",
      "price": "19.99",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0001G8",
      "onhold": false,
      "bought": false
    },
    "Velvet Pumpkin": {
      "img": "",
      "price": "14.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0001H0",
      "onhold": false,
      "bought": false
    },
    "Floral Metal Scooper": {
      "img": "",
      "price": "36.00",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0001JT",
      "onhold": false,
      "bought": false
    },
    "Bon Bon Pressed Glass": {
      "img": "",
      "price": "10.00",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0001PL",
      "onhold": false,
      "bought": false
    },
    "Fall chickadee": {
      "img": "",
      "price": "15.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0001R0",
      "onhold": false,
      "bought": false
    },
    "Pumpkin napkin (4pk)": {
      "img": "",
      "price": "24.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0001TP",
      "onhold": false,
      "bought": false
    },
    "29\" Black Cat Stake": {
      "img": "",
      "price": "28.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0001VO",
      "onhold": false,
      "bought": false
    },
    "Set of 3 Pumpkin Blocks": {
      "img": "",
      "price": "14.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0001VR",
      "onhold": false,
      "bought": false
    },
    "Turkey wine glass": {
      "img": "",
      "price": "12.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'00020G",
      "onhold": false,
      "bought": false
    },
    "Large pink pumpkin": {
      "img": "",
      "price": "26.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'00027C",
      "onhold": false,
      "bought": false
    },
    "Lg cement pumpkin": {
      "img": "",
      "price": "10.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'00027E",
      "onhold": false,
      "bought": false
    },
    "Harvest gatherings dessert plate": {
      "img": "",
      "price": "12.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'000295",
      "onhold": false,
      "bought": false
    },
    "Velvet pumpkin with stem": {
      "img": "",
      "price": "24.00",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'00029H",
      "onhold": false,
      "bought": false
    },
    "Velvet pumpkin 7.5\" round": {
      "img": "",
      "price": "15.00",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0002DI",
      "onhold": false,
      "bought": false
    },
    "48\" Willow Eucalyptus Garland in Green": {
      "img": "",
      "price": "15.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0002G2",
      "onhold": false,
      "bought": false
    },
    "11\" velvet pumkin - Brown": {
      "img": "",
      "price": "28.00",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0002GB",
      "onhold": false,
      "bought": false
    },
    "Oval Halloween pics": {
      "img": "",
      "price": "12.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0002Z5",
      "onhold": false,
      "bought": false
    },
    "Large Velvet Pumpkin": {
      "img": "",
      "price": "14.95",
      "single": false,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0002ZP",
      "stock": 9,
      "itemsOnHold": 0,
      "itemsBought": 0
    },
    "Medium Velvet Pumpkin": {
      "img": "",
      "price": "12.95",
      "single": false,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0002ZR",
      "stock": 3,
      "itemsOnHold": 0,
      "itemsBought": 0
    },
    "Pumpkin and Pearl Earrings": {
      "img": "",
      "price": "12.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'0002ZZ",
      "onhold": false,
      "bought": false
    },
    "Halloween Earrings": {
      "img": "",
      "price": "12.95",
      "single": false,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'000301",
      "stock": 3,
      "itemsOnHold": 0,
      "itemsBought": 0
    },
    "Fall Flag": {
      "img": "",
      "price": "18.99",
      "single": false,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'000308",
      "stock": 3,
      "itemsOnHold": 0,
      "itemsBought": 0
    },
    "Fall Pillow Swap": {
      "img": "",
      "price": "18.95",
      "single": false,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'00034D",
      "stock": 5,
      "itemsOnHold": 0,
      "itemsBought": 0
    },
    "Hydrangea Mini": {
      "img": "",
      "price": "15.95",
      "single": false,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'00034J",
      "stock": 2,
      "itemsOnHold": 0,
      "itemsBought": 0
    },
    "Fall Ball Tailgate tin sign": {
      "img": "",
      "price": "19.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'00034M",
      "onhold": false,
      "bought": false
    },
    "Set of 3 Bamboo Leaf  Trivets/Home Decoration": {
      "img": "",
      "price": "12.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'00034O",
      "onhold": false,
      "bought": false
    },
    "Pink and White Stripe and Dotted Pumpkin": {
      "img": "",
      "price": "24.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'00034W",
      "onhold": false,
      "bought": false
    },
    "Medium Pink Metal Pumpkin": {
      "img": "",
      "price": "24.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'00034Y",
      "onhold": false,
      "bought": false
    },
    "Pink/White/Glitter Metal Pumpkin": {
      "img": "",
      "price": "19.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'000351",
      "onhold": false,
      "bought": false
    },
    "Fall Floral Arragement": {
      "img": "",
      "price": "34.95",
      "single": true,
      "specials": [],
      "consignerName": "",
      "cosignerEmail": "",
      "profitSplit": "100/0",
      "barcode": "'00035U",
      "onhold": false,
      "bought": false
    }
  },
}
}

var consignors = [ { "name": "Anna Mae Robinson", "email": "niftynymphdesigns@gmail.com", "address": "14704 Austin Ct. Chester VA 23832", "phone": "804-840-0242", "split": "12/88", "lastLogin": 1756668900000, "password": "password", "owedProfit": 0.0 }, { "name": "Tammy Reams", "email": "tammyreams07@comcast.net", "address": " ", "phone": "804-572-7457", "split": "12/88", "lastLogin": 1757010060000, "password": "password", "owedProfit": 0.0 }, { "name": "Penny Durrett", "email": "pd609496@gmail.com", "address": " ", "phone": "8042058014", "split": "12/88", "lastLogin": 1757008200000, "password": "password", "owedProfit": 0.0 }, { "name": "Jennifer Klein", "email": "jenniferlklein248@gmail.com", "address": "16130 Church Street Amelia Court House VA 23002", "phone": "8043396602", "split": "35/65", "lastLogin": 1740968280000, "password": "password", "owedProfit": 0.0 }, { "name": "Kevin Alexander", "email": "roodboy325@yahoo.com", "address": " ", "phone": "804-651-9250", "split": "12/88", "lastLogin": 1740787200000, "password": "password", "owedProfit": 0.0 }, { "name": "Davis Durrett", "email": "davisfurniturerva@gmail.com", "address": "11646 Timberly Way Henrico VA 23238", "phone": "8042058015", "split": "12/88", "lastLogin": null, "password": "password", "owedProfit": 0.0 }, { "name": "Kristina Muniz", "email": "kristinamead09@gmail.com", "address": "55 Amethyst Way Palmyra VA 22963", "phone": "5407356992", "split": "35/65", "lastLogin": 1755967500000, "password": "password", "owedProfit": 0.0 }, { "name": "Relics Rhinestones", "email": "relicstorhinestones@gmail.com", "address": "15631 Mosaic Creek Blvd. Richmond VA 23238", "phone": "8045513352", "split": "12/88", "lastLogin": 1755857880000, "password": "password", "owedProfit": 0.0 }, { "name": "Valerie Boyer", "email": "valerieaboyer@yahoo.com", "address": "15631 Mosaic Creek Blvd Henrico VA 23238", "phone": "8045513352", "split": "50/50", "lastLogin": 1755857880000, "password": "password", "owedProfit": 0.0 }, { "name": "Jacob Clayton", "email": "jacobclayton83@gmail.com", "address": "10148 Berrymeade Place Glen Allen VA 23060", "phone": "8048734582", "split": "12/88", "lastLogin": null, "password": "password", "owedProfit": 0.0 }, { "name": "Andrew D' Andrea", "email": "andrewgem89@gmail.com", "address": "9901 Trebeck Rd N chesterfield VA 23236", "phone": "630-643-3393", "split": "12/88", "lastLogin": 1746435420000, "password": "password", "owedProfit": 0.0 }, { "name": "Kathleen Reid", "email": "kreid6158@gmail.com", "address": "7900 Kentucky Derby Drive Midlothian VA 23112", "phone": "804-243-4445", "split": "35/65", "lastLogin": 1756389240000, "password": "password", "owedProfit": 0.0 }, { "name": "Carissa Byrne", "email": "thatsbecca@gmail.com", "address": "1416 Willow Point3 Ct Virginia Beach VA 23464", "phone": "804-715-7512", "split": "12/88", "lastLogin": null, "password": "password", "owedProfit": 0.0 }, { "name": "Roberta Ferris", "email": "Rf101@yahoo.com", "address": " ", "phone": "804-683-5210", "split": "35/65", "lastLogin": null, "password": "password", "owedProfit": 0.0 }, { "name": "Judy Reid", "email": "breid00@verizon.net", "address": "7900 Kentucky Derby Drive Midltohian VA 23112", "phone": "804-484-9532", "split": "35/65", "lastLogin": null, "password": "password", "owedProfit": 0.0 }, { "name": "Rhonda Balderson", "email": "rkbalderson@gmail.com", "address": "2846 Summerchase Lane Goochland VA 23063", "phone": "804-314-0644", "split": "35/65", "lastLogin": 1756434300000, "password": "password", "owedProfit": 0.0 }, { "name": "Rachel Poindexter", "email": "rachpoin@gmail.com", "address": "1904 Shenandoah Avenue Richmond VA 23226", "phone": "804-647-9322", "split": "35/65", "lastLogin": null, "password": "password", "owedProfit": 0.0 }, { "name": "Tina Brown", "email": "Tinaterrybrown@yahoo.com", "address": "4902 Regina Rd Sandston Va 23150", "phone": "406-531-1200", "split": "12/88", "lastLogin": 1757006760000, "password": "password", "owedProfit": 0.0 }, { "name": "Ronald Romanosky", "email": "rroman_8703@comcast.net", "address": "8703 Traditional Court Henrico VA 23294", "phone": "804-461-1157", "split": "35/65", "lastLogin": null, "password": "password", "owedProfit": 0.0 }, { "name": "Lori Bilter", "email": "flourlesscakes@gmail.com", "address": "3005 Quail roost Drive Glen Allen VA 23059", "phone": "804-370-2587", "split": "35/65", "lastLogin": 1756849980000, "password": "password", "owedProfit": 0.0 }, { "name": "Cindy Hurdle", "email": "lainey1937@gmail.com", "address": "4671 Bluff Turn Marshall VA 20115", "phone": "540-272-0423", "split": "35/65", "lastLogin": 1756750140000, "password": "password", "owedProfit": 0.0 }, { "name": "Rebecca Byrne", "email": "rabyrne@email.peace.edu", "address": " ", "phone": "804-715-7514", "split": "12/88", "lastLogin": 1754713380000, "password": "password", "owedProfit": 0.0 }, { "name": "Tiffany Allen", "email": "tiffany.kingallen1304@gmail.com", "address": "2215 Silver St Aylett Va 23009", "phone": "804-247-0794", "split": "35/65", "lastLogin": 1747711980000, "password": "password", "owedProfit": 0.0 }, { "name": "Julie Rogers", "email": "jjr/75@hotmail.com", "address": "8192 Carriage homes Dr. Henrico Va 23294", "phone": "804-437-6219", "split": "35/65", "lastLogin": null, "password": "password", "owedProfit": 0.0 }, { "name": "Joseph Bien-Aime", "email": "", "address": " ", "phone": "804-263-6595", "split": "35/65", "lastLogin": null, "password": "password", "owedProfit": 0.0 }, { "name": "Betsy Robinson", "email": "brobinson0410@comcast.net", "address": " ", "phone": "804-763-9681", "split": "12/88", "lastLogin": 1748653140000, "password": "password", "owedProfit": 0.0 } ]